-- ============================================================================
--  Visitor counting — shared by BOTH websites
--    • cheap-motors.com            (repo: cheap-motors9)
--    • Cars for Sale in Uganda     (repo: ssenyonga-web)
--
--  Both sites write to the SAME public.visits table in this one Supabase
--  project, so the dashboard on either site can show the numbers.
--
--  The table already exists (created by cheap-motors.com). This script only
--  brings it up to date and is SAFE TO RUN AS MANY TIMES AS YOU LIKE —
--  nothing is dropped, no existing visit data is touched or deleted.
--
--  HOW TO RUN:  supabase.com → your project → SQL Editor → New query →
--               paste all of this → Run.  It should say "Success".
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 1. The table (created only if it is somehow missing — same shape the
--    live site already uses, so the two sites stay compatible).
-- ---------------------------------------------------------------------------
create table if not exists public.visits (
  id         bigint generated by default as identity primary key,
  vid        text,          -- anonymous visitor id kept in that browser
  device     text,          -- Android phone / iPhone / Windows PC / Mac / Tablet
  source     text,          -- where they came from: google.com, facebook.com, direct…
  created_at timestamptz not null default now()
);


-- ---------------------------------------------------------------------------
-- 2. NEW: which of the two websites the visit came from.
--    Nullable on purpose — rows already recorded by cheap-motors.com stay
--    valid and that site keeps working untouched, it just leaves this empty.
-- ---------------------------------------------------------------------------
alter table public.visits add column if not exists site text;


-- ---------------------------------------------------------------------------
-- 3. Indexes so the dashboard stays fast as visits pile up.
-- ---------------------------------------------------------------------------
create index if not exists visits_created_at_idx on public.visits (created_at desc);
create index if not exists visits_vid_idx        on public.visits (vid);
create index if not exists visits_site_idx       on public.visits (site);


-- ---------------------------------------------------------------------------
-- 4. Security. Anyone's browser may ADD a visit, but ONLY you — signed in
--    with your owner account — may read them back. Nobody can edit or
--    delete rows: no update/delete policy exists, so row-level security
--    refuses those outright.
-- ---------------------------------------------------------------------------
alter table public.visits enable row level security;

drop policy if exists "anyone can record a visit" on public.visits;
create policy "anyone can record a visit"
  on public.visits for insert
  to anon, authenticated
  with check (true);

drop policy if exists "owner reads visits" on public.visits;
create policy "owner reads visits"
  on public.visits for select
  to authenticated
  using (true);


-- ---------------------------------------------------------------------------
-- 5. Check it worked — this should return one row saying how many visits
--    are stored and when the most recent one was.
-- ---------------------------------------------------------------------------
select count(*) as total_visits,
       count(*) filter (where site is null)     as from_cheap_motors_com,
       count(*) filter (where site is not null) as from_the_new_site,
       max(created_at)                          as latest_visit
from public.visits;


-- ============================================================================
--  OPTIONAL HOUSEKEEPING — not required, run by hand whenever you want.
--
--  Delete visits older than 180 days to keep the table small:
--      delete from public.visits where created_at < now() - interval '180 days';
--
--  Label the visits already recorded by the live site (otherwise they just
--  show as "cheap-motors.com" in the dashboard, which is also fine):
--      update public.visits set site = 'cheap-motors' where site is null;
-- ============================================================================
